version: "3.7"
services:
  caddy:
    image: ghcr.io/dulli/caddy:2
    container_name: caddy
    restart: unless-stopped

    networks:
      - proxy
      - ipv6

    ports:
      - 80:80
      - 443:443

    volumes:
      - ${DOCKER_DATA_PATH:-/var/docker}/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ${DOCKER_DATA_PATH:-/var/docker}/caddy/static:/srv/static
      - ${DOCKER_DATA_PATH:-/var/docker}/caddy/data:/data
      - ${DOCKER_DATA_PATH:-/var/docker}/caddy/config:/config

    environment:
      CF_API_TOKEN: ${CF_API_TOKEN}
      BASIC_AUTH_USER: ${BASIC_AUTH_USER}
      BASIC_AUTH_PASSWD: ${BASIC_AUTH_PASSWD}
      CNL_AUTH_USER: ${CNL_AUTH_USER}
      CNL_AUTH_PASSWD: ${CNL_AUTH_PASSWD}
      DOMAIN: ${DOMAIN}

    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.eth0.proxy_ndp=1

networks:
  proxy:
    name: proxy
    external: false
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.100.0.0/16
    driver_opts:
      com.docker.network.bridge.name: docker-proxy
      net.ipv4.icmp_echo_ignore_broadcasts: 0
      net.ipv4.conf.all.bc_forwarding: 1

  ipv6:
    name: ipv6
    external: false
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: fd02:fc5:9bd7::/48
# For WOL to work with the proxy network, you need to set the following commands at system level:
# sudo sysctl -w net.ipv4.icmp_echo_ignore_broadcasts=0
# sudo sysctl -w net.ipv4.conf.all.bc_forwarding=1
# sudo sysctl -w net.ipv4.conf.docker-proxy.bc_forwarding=1
