services:
  pyload:
    image: ghcr.io/dulli/pyload-ng:0
    container_name: pyload-ng
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - ${DOCKER_DATA_PATH:-/var/docker}/pyload:/opt/pyload/config
      - ${DOWNLOAD_PATH:-/var/pyload}:/opt/pyload/download
      - ${DOCKER_DATA_PATH:-/var/docker}/pyload/themes:/usr/lib/python3.11/site-packages/pyload/webui/app/themes

networks:
  proxy:
    external: true
