version: "3.5"
services:
  hyperion-ng:
    image: ghcr.io/dulli/hyperion-ng:2
    container_name: hyperion-ng
    restart: unless-stopped
    privileged: true

    ports:
      - 8090:8090 # HTTP
      - 8092:8092 # HTTPS
      - 19444:19444 # JSON-RPC
      - 19445:19445 # Protobuf

    volumes:
      - ${DOCKER_DATA_PATH:-/var/docker}/hyperion:/config
      - /dev:/dev

    # environment:
    #   - CONFIG_PATH=${CONFIG_PATH}
