services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:stable
    container_name: frigate
    restart: unless-stopped
    privileged: true
    shm_size: "64mb" # (width * height * 1.5 * 9 + 270480)/1048576 = <shm size in mb> (per Camera)
    networks:
      - proxy
    ports:
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_DATA_PATH:-/var/docker}/frigate/config:/config
      - ${DOCKER_DATA_PATH:-/var/docker}/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    devices:
      - /dev/dri/renderD128 # for intel hwaccel
      - /dev/apex_0:/dev/apex_0 # for PCIe Coral
    environment:
      FRIGATE_RTSP_PASSWORD: ${RTSP_PASSWORD}
      FRIGATE_MQTT_PASSWORD: ${MQTT_PASSWORD}
      LIBVA_DRIVER_NAME: "i965"

networks:
  proxy:
    external: true
