services:
  snapserver:
    image: ghcr.io/dulli/snapserver:0
    container_name: snapserver
    restart: unless-stopped
    hostname: docker-snapserver

    networks:
      - phy
      - proxy

    volumes:
      - config:/root/.config

volumes:
  config:

networks:
  proxy:
    external: true
  phy:
    external: true
